### ISSUE TITLE
factorio not killed on linux with steam

### ISSUE THREAD

**Issue by cleverca22** [L0laapk3/FactorioMaps#108]
while the mapping was in progress, i checked `ps aux` and confirmed the PID of factorio:
`clever   3312406  126 13.7 6591952 4492316 pts/2 Sl   05:11  13:13 /home/clever/steam-nas/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio....`

i then patched `auto.py` to log things:
```
    def kill(pid, onlyStall=False):
        print(f'kill({pid}, {onlyStall})\n')
        if pid:
            with lock:
                if not onlyStall and psutil.pid_exists(pid):
```
and it printed this at the end of the run:
`kill(3312200, False)`
but that PID didnt exist, so it didnt attempt to kill factorio!

when not in day-only mode, i think it then tries to start factorio again for night mode, and hangs because its already started

**Comment by L0laapk3** [comment]
Can you verify if the issue is solved using https://github.com/saulrh/FactorioMaps/tree/fix-process-terminate ?

**Comment by L0laapk3** [comment]
Feel free to re-open if this is still an issue
