### ISSUE TITLE
Crop freezes on fresh map

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#11]
I tend to make a save at the very start of a map before having even moved and name it something like `GregOver1a` (next one would be `GregOver1b` for example), however running the generator on that map seems to generate no images, and thus when it gets to the Cropping stage of the python script it freezes there forever.

**Comment by L0laapk3** [comment]
This should be fixed in the `dev` branch as of d65ad18b44c1146aab4c2fdc72fd59f0a3d5cc3a.
