### ISSUE TITLE
link_renderbox_area processing fail when some of the renderboxes are on surfaces that aren't being rendered

### ISSUE THREAD

**Issue by muuyo** [L0laapk3/FactorioMaps#118]
I can't make heads or tails of the error I'm getting to be honest, besides being something about "zoom" and "filename". Pastebins below, at the very least.
Log: https://pastebin.com/B2MQ8kri
Modlist: https://pastebin.com/8E3N5Xj6

Relevant error:
```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_4.3.0\auto.py", line 904, in <module>
    auto(*sys.argv[1:])
  File "C:\Users\USER\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_4.3.0\auto.py", line 723, in auto
    refZoom()
  File "C:\Users\USER\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_4.3.0\auto.py", line 703, in refZoom
    ref(outFolder, timestamp, surface, daytime, args.basepath, args)
  File "C:\Users\USER\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_4.3.0\ref.py", line 330, in ref
    path = os.path.join(link["toSurface"], daytime if link["daynight"] else "day", "renderboxes", str(surface["zoom"]["max"]), link["filename"])
KeyError: 'filename'
```

**Comment by L0laapk3** [comment]
Seems like something is going wrong with factorissimo  integration.

- Was this when appending to an existing timeline, or creating a new one?
- can you share:
  * command used
  * savefile
  * mod folder zip
I will try to reproduce it next time I work on factoriomaps (could be a while from now)

**Comment by muuyo** [comment]
Command used: python3 .\auto.py --verbose, run in an administrator Powershell terminal
exact mod folder used: [modfolder.zip](https://github.com/L0laapk3/FactorioMaps/files/12330431/modfolder.zip)
save: [gmaeoing.zip](https://github.com/L0laapk3/FactorioMaps/files/12330464/gmaeoing.zip)
Creating a new one, as there was none to iterate on (this is my first time using the program). Had to delete the output from the previous runs as it was throwing a *different* error, probably from them not finishing...
