### ISSUE TITLE
how do you make a timeline?

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [L0laapk3/FactorioMaps#12]
I managed to get this running for my savegames but I'm not getting a nice timeline like the linked example, only a snapshot of the current version. how do you get to see the factory evolution trough time?

**Comment by L0laapk3** [comment]
Can you please send me what command(s) you are using?

>

**Comment by L0laapk3** [comment]
Closed for inactivity, let me know if you have any further problems.
