### ISSUE TITLE
python2 runtime failure

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#13]
```python
  File "auto.py", line 24
    print("\r{}{}".format(arg, " " * (tsiz-len(arg))), end="\r\n" if tsiz <= len(arg) else "")
                                                          ^
SyntaxError: invalid syntax
```
This part works with python3 however.

**Comment by L0laapk3** [comment]
If you're using the latest commits, I have completely dropped python 2 in favor of python 3.

**Comment by OvermindDL1** [comment]
I am indeed using the `dev` branch, however it's readme was still speaking of python2, and I quote:

> 1. Install the latest version of [python 2.7](https://www.python.org/downloads/). (Do not install python 3.)


:-)

**Comment by OvermindDL1** [comment]
Consequently when using python 3 then instead of the commands like `python auto.py savename` instead `python3` should be used like `python3 auto.py savename` because calling `python` will call the system default where calling `python2` or `python3` will call 2 or 3 respectively.  :-)

**Comment by L0laapk3** [comment]
I should have taken care of that already as of 2bea5b85334a5723cb030eb636614186755329e0, and in the [dev branch](/L0laapk3/FactorioMaps/tree/dev) I've taken it even further by actually properly importing those functions instead of just lazily calling them. If theres still a problem in those versions, let me know. :)

**Comment by OvermindDL1** [comment]
Yep, that fixes those issues, the issue in the dev branch has with python2 is that an unsupported keyword argument was passed into the `print` call, a 3.x feature only.  I'm perfectly good with dropping python2 support though, it's ancient.
