### ISSUE TITLE
Game not outputting log properly

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#16]
When the script launches factorio the output of factorio is being placed on a single line that is constantly overwriting itself, thus making it very difficult to see what is happening.  It seems the change happened in this commit:
https://github.com/L0laapk3/FactorioMaps/commit/6d0cda09aa13da0a2e6b9af2b54f11d025ecf8b6

**Comment by L0laapk3** [comment]
Are you looking for more output from the game? In a recent commit I put a filter in place so it only prints game output with "warn", "err", "exc" in it. Or is the problem that that is actually being printed out but being overwritten?

**Comment by OvermindDL1** [comment]
A lot of useful informational messages from some mods are being silenced, especially one that takes about 2 minutes to run (a *lot* of preprocessing) and so it looks like it freezes on loading during that time.  An option to display without filtering would be useful, or perhaps to just filter known useless log messages instead?
