### ISSUE TITLE
Other Surfaces support

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#18]
Would it be possible to generate the chunks for all loaded surfaces as well?  It would be useful to see Factorissimo buildings as well as a few others that this pack has.

**Comment by OvermindDL1** [comment]
Would I'd actually find quite funny is if specialized support was done for Factorissimo and had an option to overlay it's internal contents on the building itself, scaled down to fit.  ^.^

Though I still have other surfaces from other mods as well.

**Comment by L0laapk3** [comment]
Currently a lot of the code actually supports other surfaces, but I wouldn't be suprised if I missed a thing here or there, I've never tested it on other surfaces. The idea was that it would just capture the surface you are currently standing on.

 if you have a good easy to set up example I wouldnt mind messing around with it when I have some free time :p

**Comment by L0laapk3** [comment]
The reason that bug exist is because I half ass implemented this feature so yeah :P

**Comment by OvermindDL1** [comment]
Lol, that works.  ^.^

**Comment by L0laapk3** [comment]
Should be fixed as of 3c3b5469378255bd511376e25172d5b1d8071d0c.

**Comment by L0laapk3** [comment]
See #20
