### ISSUE TITLE
Loading a save game that's saved while the current player is on another surface freezes the script

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#19]
I loaded a save while inside a factorissimo building and after printing the last line from the factorio program output it just never did anything else after it printed this:

```python
Processing GregOver2/19/Factory/floor/8/day (1 of 2)
```
Nothing ever happened.  Had to load the save, exit the building, then save again and run it.

**Comment by L0laapk3** [comment]
Same as #18
