### ISSUE TITLE
No proper confirmation on when factorio is actually done writing the screenshots to disk.

### ISSUE THREAD

**Issue by IIPoliII** [L0laapk3/FactorioMaps#23]
Hello, i have founded out after the corp process it stays blocked at 99.9% during a long time i was asking me why here is a print screen : https://i.imgur.com/Gv26fiw.png

**Comment by L0laapk3** [comment]
Does it continue after a while? Or is it really stuck? How long have you waited? This generally has to do with the way factorio handles file outs and theres not much I can do about it if it just takes long at the end, if it doesnt output at all that might be a different story.

**Comment by IIPoliII** [comment]
I waited for about 30 minutes now but maybe i need to wait more what's weird is that factorio "already" got killed. But i think factorio finished the corp but what does this function do? Is it an compressing one? Because right now the folder is 16 Gb but the map isn't that big. It's an update of an map. I already did it with an old version of the map 1 month ago and the folder was only 1 Gb, i didn't added tons of entities to the map too just a few updates.

**Comment by L0laapk3** [comment]
Crop does not compress, its normal that the output folder is quite a bit larger than before its finished. Its quite likely that its getting stuck because factorio did not properly output all screenshot images

**Comment by L0laapk3** [comment]
I personally never have this problem but I've had at least one other report of factorio actually not outputting every single image properly. Later I can try something to fix this, but it will probably take some iterations to get right as I cannot try the fix myself.

**Comment by IIPoliII** [comment]
Yes I understand is it maybe possible that I send you any logs about this? And it's weird it gets stuck so long, also it does not use any ressources (CPU, Ram,... ) While it's stuck

**Comment by L0laapk3** [comment]
It likely has to do with factorio storing files out of the order that they were made in on some systems. Im not entirely sure how to properly fix this, I'll have to have a chat with the devs when they have some time, I need to somehow get feedback to see when factorio is done saving screenshots. I'll let you know when theres something you can test.

**Comment by IIPoliII** [comment]
Okay thanks !

**Comment by L0laapk3** [comment]
I've made some changes on the dev branch: b346d17ec9102704d77811181cce69bd2af926a6 which can potentially fix this. If you'd like to try them, let me know if it makes a difference or not :)

**Comment by L0laapk3** [comment]
Hey, Ive published a potential fix on my [dev branch](https://github.com/L0laapk3/FactorioMaps/tree/1b1b6305e3294a75f569a4d065b95ddc81a81521). Mind giving it a try and letting me know if it still gets stuck at 99% cropping?

**Comment by IIPoliII** [comment]
Hai, i tried again but i get this error again of writing permissions. It's weird i changed that everyone can write in it and factorio IS somehow able to write to it it's just the script-output folder who is making issues it looks like a link folder. Here is the log and a picture of the folder 
![image](https://user-images.githubusercontent.com/29628512/53292723-21681680-37c7-11e9-93f9-602c88f1d66b.png)

**Comment by IIPoliII** [comment]
it's weird i get it on multiple pcs and sadly i can't test on my laptop right now

**Comment by IIPoliII** [comment]
Okay the issue for writing permissions is not the "writing"problem here i present you the 3 posibility to fix it for the next user : 

1. Run the game once and re-save the game
2. Create an script-output folder at the factorio root
3. Change permissions on %appdata%/local/Temp

**Comment by IIPoliII** [comment]
I am trying the new version of the dev branch

**Comment by L0laapk3** [comment]
Were you trying to make multiple snapshots at once? I had a really nasty variable name capitalisation error breaking that one.

**Comment by IIPoliII** [comment]
`python auto.py railworld85 --factorio=D:\User\raimu\Téléchargements\Factorio_x64_0.16.51\Factorio_0.16.51\bin\x64\factorio.exe
factorio path: d:\user\raimu\téléchargements\factorio_x64_0.16.51\factorio_0.16.51\bin\x64\factorio.exe
output folder: script-output\FactorioMaps\railworld85
checking for updates
enabling FactorioMaps mod
cleaning up
building autorun.lua
starting factorio
Jonction créée pour C:\Users\raimu\AppData\Local\Temp\FactorioMaps-681651893\script-output <<===>> D:\User\raimu\Téléchargements\Factorio_x64_0.16.51\Factorio_0.16.51\script-output
[GAME]   14.181 Created atlas bitmap 8192x8136 [linear-minification, mipmap, terrain]
[GAME]   15.237 Created atlas bitmap 8192x1216 [linear-minification, mipmap, terrain]
[GAME]   38.202 Warning LuaGameScript.cpp:1545: luaremove_path error: Scripts can only use file space inside of script-output
Processing railworld85/189-2/nauvis/day (1 of 2)
crop 100.0% [=====================================================================================]
disabling FactorioMaps mod
cleaning up
Traceback (most recent call last):
  File "auto.py", line 400, in auto
    refZoom()
  File "auto.py", line 395, in refZoom
    ref(outFolder, otherInputs[0], otherInputs[1], otherInputs[2], basepath, **kwargs)
  File "D:\User\raimu\Téléchargements\Factorio_x64_0.16.51\Factorio_0.16.51\mods\L0laapk3_FactorioMaps_3.1.2\ref.py", line 200, in ref
    treshold = .3 * Image.open(os.path.join(toppath, "Images", *compareList[0]).replace(ext, outext)).size[0] ** 2
  File "D:\Python3\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../../script-output\\FactorioMaps\\railworld85\\Images\\189\\nauvis\\day\\20\\-1\\-1.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto.py", line 553, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 540, in auto
    rmtree(tmpDir)
  File "D:\Python3\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\Python3\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\Python3\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\raimu\\AppData\\Local\\Temp\\FactorioMaps-681651893\\factorio-current.log'`

In french it means this proccess cannot acces to the file because it's used by another folder

**Comment by IIPoliII** [comment]
i only tried one snap shot of my railworld

**Comment by L0laapk3** [comment]
It looks like that error is caused by a "bricked" state left behind in the output folder by a previous crash. I've just pushed a new version to dev that I think is ready for release if it fixes this. Can you try again, but this time `--delete` the output folder? Thanks!

**Comment by IIPoliII** [comment]
oh yes it's possible it's this forgot about that i try right now!

**Comment by IIPoliII** [comment]
For now  the script is running and the end of the corp process worked. So now i await the full result but the issue is fixed i close it when it's finished and all is working anyway thanks for your help and time you took in my issue !

**Comment by IIPoliII** [comment]
Do you see that ? 
![image](https://user-images.githubusercontent.com/29628512/53293224-2087b280-37d0-11e9-8ec1-46f6168bec85.png)

This is the absolute beauty ! Thanks Issue Closed.

**Comment by L0laapk3** [comment]
Theres still another version of this issue that I haven't yet resolved, its possible that images only start existing after they were scanned for the zoom layer, and thus missing in higher zoom levels. I need dev confirmation on a proper solution for that so I'll leave the issue open for now.

**Comment by IIPoliII** [comment]
Sure okay for now i gonna focus on bigger maps problems

**Comment by L0laapk3** [comment]
https://forums.factorio.com/viewtopic.php?f=65&t=65045

**Comment by IIPoliII** [comment]
The post was removed?

**Comment by L0laapk3** [comment]
What?

**Comment by IIPoliII** [comment]
@L0laapk3 The link says me the post don't exsists anymore at least the link don't work anymore

**Comment by IIPoliII** [comment]
Any news c:

**Comment by L0laapk3** [comment]
Its on my 0.17 todo list (#28 ), however I've kinda lost interest in this project right now, Sorry.

**Comment by L0laapk3** [comment]
I've made some changes that have the potential to fix this in 3c78e907b7b110a0082d788d2bd3e2449bbbd166. If you want to try it, let me know if it still gets stuck on cropping 99% occasionally :)

**Comment by IIPoliII** [comment]
Sure i check that once i am at home, i forgot my portable pc alimentation so i can't do it here if you want some test maps to check it out you can found some here : https://saves.joinandplaycoop.com/#Home%2FS1%2FEnd%20Map%20Saves
You can take a big one like the 180 MB one. The hard part with those maps is that actually spawn are separated so it will need blanks between the bases but it should work last time it did. 

Thanks for working on it again and i try tonight !

**Comment by IIPoliII** [comment]
So it worked really well, the write was fast for such an huge map but now i got trought an error about the map view.
So this is the view of the map in factorio : 
![image](https://user-images.githubusercontent.com/29628512/55096362-06384180-50ba-11e9-8601-f087b4dfe0e9.png)
but if you check on the map view here : 
http://test.joinandplaycoop.com/maps/20-Mar-19_20/index.html#1/nauvis/16/-8292/-2823/0/24
you can see a part is missing

**Comment by L0laapk3** [comment]
Thats strange lol, you got a save file for that?

**Comment by IIPoliII** [comment]
Yes there https://saves.joinandplaycoop.com/Home/S1/End%20Map%20Saves/20-Mar-19:20.zip

**Comment by L0laapk3** [comment]
That was caused by an entirely different issue related to multiple forces, I've taken care of it with release v3.3.1.

Is the "cropping stuck at 99%" issue completely gone now? :D

**Comment by IIPoliII** [comment]
Oh nice okay! Yeah I saw that the dev branch is 0.3.3.0 (had to rename the mod folder xD)

But the corping thing is fixed yes I confirm so this issue can be closed I let you the joy of doing it c: !

**Comment by L0laapk3** [comment]
After confirming this with some other people who previously had this problem im glad to say that I think I hope its fixed for good now :p
