### ISSUE TITLE
Separate map tags to snapshot level

### ISSUE THREAD

**Issue by L0laapk3** [L0laapk3/FactorioMaps#27]
Map tags could potentially have different textures when the mods are changed troughout versions.

**Comment by xiagu** [comment]
Is this related to tags showing up in every snapshot, even before they were created or after they were removed?

For example, this is the first snapshot for this game, but all the tags from later snapshots are still shown:
![image](https://user-images.githubusercontent.com/4063719/54077685-eb1fa200-4270-11e9-957c-7f5cc643504d.png)

**Comment by L0laapk3** [comment]
Yep. The back end is there, the front end is not.

**Comment by L0laapk3** [comment]
Yep. The back end is there (so all the data is stored correctly so it'll work with future versions), but the front end has yet to be written.
