### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by ktllo** [L0laapk3/FactorioMaps#39]
The auto.py crash after the image are generated. No index.html and related program can be found in script-output. 

Traceback (most recent call last):
  File "auto.py", line 629, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 568, in auto
    newImg = ImageChops.multiply(newImg, Image.new("RGBA", img.size, color=tuple(map(lambda s: int(round(float(s))), iconColor[1].split("%")))))
AttributeError: 'NoneType' object has no attribute 'size'

Python version: 3.7.3
OS: Windows 10
Game version: 0.17.29

**Comment by L0laapk3** [comment]
Thanks for reporting. Can you please attach your save file and zipped mod
folder so I can try replicate this? Thanks.

Op vr 12 apr. 2019 15:15 schreef LO Kam Tao Leo <notifications@github.com>:

**Comment by ktllo** [comment]
Please download the save and mods here" http://www.leolo.pro/fileshare/a06fedaa-7cbc-4334-b7b7-8fbc7f589cdd/Factorio.zip

**Comment by L0laapk3** [comment]
Sorry for the lack of response. I got caught up in stuff and then forgot about it. This should have been fixed by Wyrrrd as of #25c034e8d5b5911927ced2afe119db04108850f9 .
