### ISSUE TITLE
syntax error in auto.py

### ISSUE THREAD

**Issue by skelgaard** [L0laapk3/FactorioMaps#41]
File "auto.py", line 112
    print(f"PID: {pid}")
                      ^
SyntaxError: invalid syntax

**Comment by skelgaard** [comment]
and  one more
  File "auto.py", line 175
    print(f'Bad flag: "{key}"')

**Comment by skelgaard** [comment]
File "auto.py", line 176
    raise ValueError(f'Bad flag: "{key}"')

**Comment by skelgaard** [comment]
seems to be loads of errors
  File "auto.py", line 396
    f'fm.autorun = {{\n'

**Comment by L0laapk3** [comment]
Sounds like you are using python 2. Python 3 is required for this mod.

**Comment by skelgaard** [comment]
python3 -v
Python 3.5.3 (default, Sep 27 2018, 17:25:39)

$ python3 auto.py
  File "auto.py", line 396
    f'fm.autorun = {{\n'
                       ^
SyntaxError: invalid syntax

**Comment by L0laapk3** [comment]
Sorry, I'm using features introduced python 3.6. I'll update the readme to reflect this. Please update your python :]

**Comment by skelgaard** [comment]
ok i can only get python 3.5 on my debian machine, and am not going to run testing on a production machine

**Comment by L0laapk3** [comment]
If you're commited, you can change all the f strings to normal string
concatenations, it should (?) work for you then :)

**Comment by skelgaard** [comment]
nah i will wait.. seems there is around 1 month to release of next debian which have 3.7 in it... just a shame.. wanted to test it on my servers, but can't now then

**Comment by L0laapk3** [comment]
You will probably encounter one or two problems with platforms other than windows, at the very least #37. I'm trying my best to keep, etc unix compatible but I sometimes mess it up
