### ISSUE TITLE
Mod no longer works(3.5.0), Factorio(1.17.69)

### ISSUE THREAD

**Issue by GustJc** [L0laapk3/FactorioMaps#50]
After installing the mod, version 3.5.0, I can no longer load or start any game, instead I get this message.
![factorio_bug](https://user-images.githubusercontent.com/3084189/66354284-b543b880-e93a-11e9-8d59-a9163a8aa407.jpg)

This only happens with version 3.5.0. I tried with 3.4.0 and I could start and load just fine.

Extra info:
The FactorioMaps is the only mod installed.
Installed from the ingame modManager, but also tried from the released download on github.
Factorio version: 0.17.69(build 47194, win64, steam)

**Comment by L0laapk3** [comment]
It looks like autorun.lua is not getting created. What command are you using to invoke the mod? Which OS are you using? Whats your python version? (`python --version`)

**Comment by L0laapk3** [comment]
Are you using the command, or just opening factorio? In the latter case, I found an issue which prevented the introduction dialog from showing up but does not prevent the mod from generating maps. I've fixed this in 3.5.1. If you believe it's something els, feel free to re-open.

**Comment by GustJc** [comment]
Thanks.... I was just opening factorio and trying to start a new game, I did open any console window or execute any command.
Using Windows 10 and Python 3.7.2
