### ISSUE TITLE
[Suggestion] Remove smoke

### ISSUE THREAD

**Issue by Trapton** [L0laapk3/FactorioMaps#6]
I do not use the mod yet, but in the live demo I noticed that the smoke is in the map.
You can not do anything with Google Maps, but at Factorio it would be better without smoke.

https://i.imgur.com/3jSIErM.jpg

**Comment by L0laapk3** [comment]
![image](https://user-images.githubusercontent.com/6313423/46612852-f891fe00-cb11-11e8-8856-19c791dc6ddf.png)
I have considered it, but I decided to leave it in as power plants would just not look the same at all without it.
I'm still dwelling over if I should set lock wind speed and direction to a favorable position everytime. But the main thing stopping me from doing this is that I'd have to let the game run for 10-20 seconds or so before taking the snapshot. This would stop you from timing a save at a certain event, for example a rocket launch
