### ISSUE TITLE
Setting site to display oldest time first?

### ISSUE THREAD

**Issue by Tataru-Taru** [L0laapk3/FactorioMaps#65]
Hello,

Since this wasn't an urgent issue, I didn't want to hassle you on discord. Is there a change I can make so that when the site loads up, it picks the oldest time, so then people can slide it watching it grow?

At the moment it loads the newest time, so sliding back to a less built base isn't as exciting.

Thank you for your time and thank you again for putting this mod together.

**Comment by L0laapk3** [comment]
It's supposed to do that already, I will look into it when I have some more time. :)

**Comment by L0laapk3** [comment]
It appears to still do that correctly, did you host the timeline somewhere?

**Comment by L0laapk3** [comment]
is the issue resolved?

**Comment by sonowz** [comment]
I'm currently using an old version (3.5.3) and I manually patched `index.js` file like this:
https://github.com/L0laapk3/FactorioMaps/blob/36cb312393d16a55aa1f9294a4b11c1979790fe9/web/index.js#L575
to
```
initial: 0,
```
And it works.

**Comment by L0laapk3** [comment]
Are you hosting the timeline publicly somewhere? I would like to investigate why it wasn't already working.
Did you scan the maps in the correct order?

**Comment by sonowz** [comment]
You can check patched page [here](http://61.74.24.50/factorio/industrial).
Note: this site was generated using the mod version 3.5.3 release.
