### ISSUE TITLE
Map label image sizes are inconsistent

### ISSUE THREAD

**Issue by sonowz** [L0laapk3/FactorioMaps#69]
Example:

![image](https://user-images.githubusercontent.com/18653427/81492585-ec64b880-92d3-11ea-9e6c-750241ea79f3.png)

Images from some mods (above is benzene icon from Angel's) appears huge in maps.

It turns out that images in `%map_output_directory%/Images/labels` have different resolutions,
where vanilla = 64x64 pixels, but others differ from 32x32 to 596x596(that benzene).

Manually changing image resolution to 64x64 fixes the issue.

**Comment by L0laapk3** [comment]
Can you attach a link of this map if you have it public?

**Comment by sonowz** [comment]
Thank you for fixing this! 👍

**Comment by L0laapk3** [comment]
No problem! :)
