### ISSUE TITLE
Feature request: compression

### ISSUE THREAD

**Issue by maxsupermanhd** [L0laapk3/FactorioMaps#76]
Compress png files and unpack it on client side to save storage on server (megabases up to 9gb).
Ready to take time to make compression/decompression algorithm for that using pre-defined dictionary.

**Comment by L0laapk3** [comment]
as discussed on discord:
Closed as I personally have no intention of implementing this, but I'd be open to a potential PR that implements image compression based on some dictionary of sorts :)
