### ISSUE TITLE
[Bug] Mod prevent to load any Savegame ^^

### ISSUE THREAD

**Issue by H4nSolo** [L0laapk3/FactorioMaps#78]
Hi, i want to test the Mod but after downloding and installing it from the Mod Website of Facotrio, a can't load any Savegames ^^

[Image of the Error](https://imgur.com/8F8Xmtx)

Game Version: 0.18.32
Installed Mods: 110 (without the base Mod)

List of Mods:

> 
> 1: 2x2-Chest
> 2: A Sea Block Config
> 3: aaa-log-active-mods
> 4: Advanced-Solar
> 5: AfraidOfTheDark
> 6: angels-smelting-extended
> 7: angelsaddons-oresilos
> 8: angelsaddons-petrotrain
> 9: angelsaddons-pressuretanks
> 10: angelsaddons-warehouses
> 11: angelsbioprocessing
> 12: angelsindustries
> 13: angelspetrochem
> 14: angelsrefining
> 15: angelssmelting
> 16: AutoDeconstruct
> 17: beautiful_bridge_railway
> 18: belt-reverser
> 19: Better-Power-Armor-Grid
> 20: BigBags
> 21: BigFluidWagon
> 22: BlueprintExtensions
> 23: blueprint_flip_and_turn
> 24: bobassembly
> 25: bobelectronics
> 26: bobenemies
> 27: bobinserters
> 28: boblibrary
> 29: boblogistics
> 30: bobmining
> 31: bobmods_gfxtweak
> 32: bobmodules
> 33: bobplates
> 34: bobpower
> 35: bobrevamp
> 36: bobtech
> 37: bobvehicleequipment
> 38: bobwarfare
> 39: ChangeMapSettings
> 40: CircuitProcessing
> 41: Compilatron
> 42: Crafting_Speed_Research
> 43: DragonIndustries
> 44: easy-wind-turbine
> 45: EasyCreative
> 46: Electric Furnaces
> 47: EnableResearchQueue
> 48: enhanced-pipette
> 49: even-distribution
> 50: even-longer-inserters
> 51: Exoskeleton Mark II
> 52: Explosive Excavation
> 53: factorio-reach
> 54: Factorissimo2
> 55: FastLongInserters
> 56: flib
> 57: Flow Control
> 58: fluid-void-extra
> 59: FluidFilter
> 60: FluidMustFlow
> 61: fluid_permutations
> 62: FNEI
> 63: HandyHands
> 64: helmod
> 65: industrial-engineering
> 66: infinite_buffer_fluid_tank
> 67: Inventory Sensor
> 68: jetpack
> 69: KS_Power
> 70: LandfillPainting
> 71: LaneBalancer
> 72: LoaderRedux
> 73: LogisticTrainNetwork
> 74: LtnManager
> 75: LTN_Combinator
> 76: manual-inventory-sort
> 77: miniloader
> 78: Nanobots
> 79: nice-try-train
> 80: nixie-tubes
> 81: NoRespawnGun
> 82: Noxys_Waterfill
> 83: Nuclear Fuel
> 84: OpteraLib
> 85: Orphan Finder
> 86: PavementDriveAssist
> 87: PersonalTeleporter
> 88: Power Armor MK3
> 89: qol_research
> 90: railloader
> 91: RaiLuaLib
> 92: reverse-factory
> 93: ScienceCostTweakerM
> 94: SeaBlock
> 95: ShinyAngelGFX
> 96: ShinyBobGFX
> 97: some-corpsemarker
> 98: SpaceMod
> 99: Squeak Through
> 100: stdlib
> 101: StorageTank2
> 102: TarawindBeaconsRE
> 103: Teleporters
> 104: textplates
> 105: TimeTools
> 106: TLBE
> 107: UltimateBelts_Owoshima_And_Pankeko-Mod
> 108: VehicleSnap
> 109: VoidChestPlus
> 110: Warehousing

**Comment by L0laapk3** [comment]
Thats not my mod lol. You can download factoriomaps from the mod portal or
from https://github.com/L0laapk3/FactorioMaps/releases
