### ISSUE TITLE
How do I stop/deactivate/uninstall factoriomaps

### ISSUE THREAD

**Issue by Neutora** [L0laapk3/FactorioMaps#79]
I followed the instructions and run python auto.py (factorio was closed) and recieved this error message in cmd

...\Factorio\mods\L0laapk3_FactorioMaps_4.1.0>python auto.py
Traceback (most recent call last):
  File "auto.py", line 5, in <module>
    raise Exception("64 bit Python 3.6 or higher is required for this script.")
Exception: 64 bit Python 3.6 or higher is required for this script.

I have Python 3 Version 3.8.3150.0 installed. I closed cmd and started factorio again but everything was stuck and I received this message:
![FactorioMaps Stuck](https://user-images.githubusercontent.com/38799154/86272790-6d06ad80-bbcf-11ea-89e7-02e95b8ec918.JPG)

I  waited for over an hour and tried again but nothing changed. My save was only 5MB.

To test this mod, I made a new save, to prevent any corruption but now even my other saves are stuck and give me the same message. Even if I make a new save, it is stuck and I get the same error message. 

How do I fix this and stop/delete this program?

**Comment by L0laapk3** [comment]
To answer the first error:
You are using the wrong python version to run the script, chances are that even tho also you have python 3.8 installed, typing `python --version` will give you an older version of python that you also have installed. Try uninstalling the older python and then reinstall python 3.8, while ensuring that "add python to path" is selected in the installer.

But it seems like it managed to run at least once and terminated it improperly, as an autorun.lua has been created at some point. Simply disable the mod in the factorio mod list. Auto.py will enable it again automatically as needed.

If you have any savefiles that you do not have a backup of and are in a bricked state, feel free to upload them online, i'll try my best to fix them again.

**Comment by Neutora** [comment]
Sorry about overreacting. I thought for a moment ALL my saves were corrupted.
I deleted the mod .zip and the mod folder and restarted my PC. My other saves are running again. The current one was just a test save with a few minutes playtime, so it does not matter. 

I am sure it is a great mod and I might even try it again in the future, but I think even with the instructions it is difficult to use for people without any programming knowledge. 

Thanks for the fast reply and all the work that went into creating this.
