### ISSUE TITLE
Is it possible to render the entire map?

### ISSUE THREAD

**Issue by 0xRainy** [L0laapk3/FactorioMaps#80]
Is there some settings that will render all visited chunks?

Would like to get a map of the entire explored area, even if I haven't built something there.

**Comment by L0laapk3** [comment]
You can use `--build-range=100 --connect-range=100`. (Or maybe higher)

**Comment by 0xRainy** [comment]
Thanks for the response, I'll try that

**Comment by L0laapk3** [comment]
np, enjoy :)
