### ISSUE TITLE
Still instant crash

### ISSUE THREAD

**Issue by Luke-101** [L0laapk3/FactorioMaps#84]
Hello, for the 1.0 update of Factorio I returned to it and started the game when I saw in the mod list this mod and remembered the error that I had I tried to fix it, but it instant crash the game.

What I have done:
- installed (upgrade) this version of python (https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe)
- created a new save file with the mod disabled (skipped the 1.0 initial cutscene)
- exited factorio
- started the mod with the command prompt (without Admin Privilages)
- accepted the steam warning message

<details>
  <summary>LOG</summary>
C:\Users\SM\AppData\Roaming\Factorio\mods\L0laapk3_FactorioMaps_4.1.0>python auto.py --factorio="D:\PC GAMES\SteamLibrary\steamapps\common\Factorio\bin\x64\factorio.exe"
checking for updates
No save name passed. Using most recent save: test
factorio path: D:\PC GAMES\SteamLibrary\steamapps\common\Factorio\bin\x64\factorio.exe
output folder: script-output\FactorioMaps\test
Enabling FactorioMaps mod
Deleting output folder (C:\Users\SM\AppData\Roaming\Factorio\script-output\FactorioMaps\test)
cleaning up
Building autorun.lua
Building config.ini
starting factorio
WARNING: Could not find steam exe. Falling back to old steam method.
         If you have any default arguments set in steam for factorio, delete them and restart the script.
         Please alt tab to steam and confirm the steam 'start game with arguments' popup.
         To avoid this in the future, use the --steam-exe argument.
Processing test/1/nauvis/day (1 of 2)
Surface prescan test/1/nauvis
Surface capture test/1/nauvis/day
crop 100.0% [=========================================================================================================]
killed factorio
cleaning up
Building autorun.lua
Building config.ini
starting factorio
WARNING: Could not find steam exe. Falling back to old steam method.
         If you have any default arguments set in steam for factorio, delete them and restart the script.
         Please alt tab to steam and confirm the steam 'start game with arguments' popup.
         To avoid this in the future, use the --steam-exe argument.
generating thumbnail
zoom 100.0% [=========================================================================================================]
zooming renderboxes 1
Surface capture test/1/nauvis/night
Processing test/1/nauvis/night (2 of 2)
crop 100.0% [=========================================================================================================]
killed factorio
zoom 100.0% [=========================================================================================================]
zooming renderboxes 1
generating mapInfo.json
updating labels
applying configuration
generating mapInfo.js
creating index.html
Disabling FactorioMaps mod
</details>

Is this a problem with the 1.0 update or is still something wrong with my computer ?

**Comment by L0laapk3** [comment]
From the output it seems like everything worked successfully. Are you positive it didn't output anything? You should hopefully find it in `C:\Users\SM\AppData\Roaming\Factorio\script-output\FactorioMaps\test`.

**Comment by Luke-101** [comment]
yes, I don't know why It didn't work before.
Thank alot for your work.
P.s. since I'm here I would ask you if there is a way to automatically make a snapshot every hour / make a snapshot while in the game ?

**Comment by L0laapk3** [comment]
It's been on my todo list for a while, see #63 :)

**Comment by Luke-101** [comment]
ok good.
Have a great day
