### ISSUE TITLE
mod not running on mac with BobAngleLTN Combo, python 3.7.4

### ISSUE THREAD

**Issue by cwaidelich** [L0laapk3/FactorioMaps#85]
Hello,

can somebody maybe point out what I am missing to run this? Here my failer log after running _python3 auto.py_.

`python3 auto.py
Traceback (most recent call last):
  File "auto.py", line 55, in <module>
    from zoom import zoom, zoomRenderboxes
  File "/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/zoom.py", line 48, in <module>
    jpeg = TurboJPEG(Path(__file__, "..", "mozjpeg/libturbojpeg.so").resolve().as_posix())
  File "/usr/local/lib/python3.7/site-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so, 6): no suitable image found.  Did find:
	/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so: stat() failed with errno=22`

Running on a mac, 10.15, Catalina.

Factorio 1.0, Map is full of mods (Bobs, Angles, LTN,...)

`python3 -m pip install -r packages.txt`
`
  Requirement already satisfied: PyTurboJPEG>=1.1.5 in /usr/local/lib/python3.7/site-packages (from -r packages.txt (line 1)) (1.4.1)
Requirement already satisfied: psutil>=5.4.8 in /usr/local/lib/python3.7/site-packages (from -r packages.txt (line 2)) (5.7.2)
Requirement already satisfied: numpy>=1.16.4 in /usr/local/lib/python3.7/site-packages (from -r packages.txt (line 3)) (1.19.1)
Requirement already satisfied: Pillow>=6.1.0 in /usr/local/lib/python3.7/site-packages (from -r packages.txt (line 4)) (7.2.0)
Requirement already satisfied: orderedset>=2.0.1 in /usr/local/lib/python3.7/site-packages (from -r packages.txt (line 5)) (2.0.3)`

```
python3 --version
Python 3.7.4
```

Please let me know if you need more information.

Thanks Christian

**Comment by L0laapk3** [comment]
Hi, it seems like the mozjpeg compiled binaries included in FactorioMaps aren't working for your mac. I've included an .exe for windows and a .so for unix, and I was under the impression that that would cover macs aswell, but it seems like this isn't the case.

Could you try to replace the existing libturbojpeg.so with https://appveyorcidatav2.blob.core.windows.net/kornel-84920/mozjpeg-4ekrx/1-0-24/p0t617txdxrspk1j/cmake_build/Release/turbojpeg.lib?sv=2015-12-11&sr=c&sig=diLX%2B9xy0iHBSxg8vdzonIfXuBXfGFPwQpPoSCvI9cw%3D&st=2020-08-20T00%3A09%3A12Z&se=2020-08-20T00%3A15%3A12Z&sp=r ? Change the file name and extension so this file replaces the old libturbojpeg.so. I'm hoping that that would do the job :p

**Comment by cwaidelich** [comment]
Hi, 

thx for the quick response, clicking on the link throws me to the following page:

![Bildschirmfoto 2020-08-20 um 11 30 31](https://user-images.githubusercontent.com/5076279/90753216-99d66780-e2d8-11ea-949e-73ffc358339c.png)

R Christian

**Comment by L0laapk3** [comment]
The link is turbojpeg.lib from https://ci.appveyor.com/project/kornel/mozjpeg-4ekrx/build/artifacts.

**Comment by cwaidelich** [comment]
Hi,

sorry for the late response, was kind of busy.

I did the follwing:

```
1)
pwd
/Users/christian/Library/ApplicationSupport/factorio/mods/L0laapk3_FactorioMaps_4.1.0

2)
mv libturbojpeg.so libturbojpeg.so.backup

3)
mv ~/Downloads/turbojpeg.lib libturbojpeg.so

4)
python3 auto.py
Traceback (most recent call last):
  File "auto.py", line 55, in <module>
    from zoom import zoom, zoomRenderboxes
  File "/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/zoom.py", line 48, in <module>
    jpeg = TurboJPEG(Path(__file__, "..", "mozjpeg/libturbojpeg.so").resolve().as_posix())
  File "/usr/local/lib/python3.7/site-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so, 6): no suitable image found.  Did find:
	/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
	/Users/christian/Library/Application Support/factorio/mods/L0laapk3_FactorioMaps_4.1.0/mozjpeg/libturbojpeg.so: stat() failed with errno=22
```

Any other ideas?

**Comment by L0laapk3** [comment]
Sorry, seems that I forgot to answer. Since this is so old now, I will close it. If you want to persue this further, feel free to reopen this.
