### ISSUE TITLE
Zooming being skipped for day only when creating a second timelapse in a save

### ISSUE THREAD

**Issue by Miyuyami** [L0laapk3/FactorioMaps#86]
I have attached the mods I'm using (helmod and evogui) [mods.zip](https://github.com/L0laapk3/FactorioMaps/files/5112349/mods.zip)

I attached 2 saves, run first one to generate first timelapse, then second one in the same folder to generate 2nd timelapse. [saves.zip](https://github.com/L0laapk3/FactorioMaps/files/5112357/saves.zip)
I also attached the logs where you can see that somehow it skips the zooming part for day after ref on 2nd timelapse. It does not skip the zooming part on night. [logs.zip](https://github.com/L0laapk3/FactorioMaps/files/5112363/logs.zip)

I have a workaround by doing a copy of the save then running it with "dayonly" and copying image folders in the day folder (without .txt files) in the timelapse of the main save.

PS: I don't know python and just describing from what I've noticed in logs. I hope it helps in finding the problem. 😊

**Comment by L0laapk3** [comment]
Hi there,

Thanks for the report and sorry for the delay. I've checked this out, and when I tried running it myself and it generated day and night images of both snapshots normally for me. Also your logs indicate that it was working properly. I'm not sure what went wrong here. After night ref step, it mentioned keeping 7k images from 12k, so by lack of alternatives I'm going to blame some weird factorio version or an antivirus :D

If you encounter this again, or have any additional information to contribute, feel free to open this again but for now I'll close this as I have no idea what to do with this.
