### ISSUE TITLE
Where is the timeline?

### ISSUE THREAD

**Issue by Saniee** [L0laapk3/FactorioMaps#88]
I managed to get this running for my savegames but I'm not getting a nice timeline like the linked example, Only the latest. 

The command what Im running is = python auto.py (MapName) --factorio=(PATH) --no-tags --default-timestamp=0

**Comment by L0laapk3** [comment]
`auto.py (MapName)` is just a shortcut for `auto.py (MapName) (MapName)`, so unless you are using a wildcard `*`, it will only find a single savefile that matches the exact string you gave it.

**Comment by Saniee** [comment]
So do I need to have more then just 1 save file?

**Comment by L0laapk3** [comment]
Correct, it loads up the savefile and renders it. Factoriomaps cannot go back in time in your savefile somehow and reconstruct older snapshots. Sorry.
