### ISSUE TITLE
Have some issuse to use this factorio mod

### ISSUE THREAD

**Issue by thanh125643** [L0laapk3/FactorioMaps#95]
I want to use it mod to make a timelapse map for my friend. He love timelapse and so do i.
But i dont think i understand this mod close enough.

I think this mod will make me a timelapse with single save file. 
Like you run it in background and if you save it game this will make a new image.
It just me wrong or it not work like it.

**Comment by L0laapk3** [comment]
Closing after working it out on discord :)
